### PR TITLE
Added Contributing.md

### PR DESCRIPTION
**Pull request by firascodes**

### CODE REVIEW

**Comment by publikphigor** [comment]
Impressive. Thanks for contributing!

**Comment by publikphigor** [comment]
Next time when you're making a pull request connected to an open issue, add a line that says "Closes #3" where 3 is the issue number.

That way the issue is automatically closed after the pull request is merged.

**Comment by firascodes** [comment]
Alright Noted!

**Comment by firascodes** [comment]
kindly edit the hacktoberfest tag as it has a typo.

**Comment by publikphigor** [comment]
Thanks for pointing it out.

**Pull request merged**
